// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cppdist_int_MtoN
arma::mat cppdist_int_MtoN(arma::mat& X, arma::mat& Y);
RcppExport SEXP _RiemSphere_cppdist_int_MtoN(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cppdist_int_MtoN(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// cppdist_ext_MtoN
arma::mat cppdist_ext_MtoN(arma::mat& X, arma::mat& Y);
RcppExport SEXP _RiemSphere_cppdist_ext_MtoN(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cppdist_ext_MtoN(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// cppdist_pair_int
arma::mat cppdist_pair_int(arma::mat& X);
RcppExport SEXP _RiemSphere_cppdist_pair_int(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cppdist_pair_int(X));
    return rcpp_result_gen;
END_RCPP
}
// cppdist_pair_ext
arma::mat cppdist_pair_ext(arma::mat& X);
RcppExport SEXP _RiemSphere_cppdist_pair_ext(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cppdist_pair_ext(X));
    return rcpp_result_gen;
END_RCPP
}
// cppdist_int_1toN
arma::vec cppdist_int_1toN(arma::vec x, arma::mat& Y);
RcppExport SEXP _RiemSphere_cppdist_int_1toN(SEXP xSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cppdist_int_1toN(x, Y));
    return rcpp_result_gen;
END_RCPP
}
// cppdist_ext_1toN
arma::vec cppdist_ext_1toN(arma::vec x, arma::mat& Y);
RcppExport SEXP _RiemSphere_cppdist_ext_1toN(SEXP xSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cppdist_ext_1toN(x, Y));
    return rcpp_result_gen;
END_RCPP
}
// engine_wmean
Rcpp::List engine_wmean(arma::cube data, std::string name, int maxiter, double eps, arma::vec weights);
RcppExport SEXP _RiemSphere_engine_wmean(SEXP dataSEXP, SEXP nameSEXP, SEXP maxiterSEXP, SEXP epsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(engine_wmean(data, name, maxiter, eps, weights));
    return rcpp_result_gen;
END_RCPP
}
// rvmf_h
NumericVector rvmf_h(double n, double ca, double d1, double x0, double m, double k, double b);
RcppExport SEXP _RiemSphere_rvmf_h(SEXP nSEXP, SEXP caSEXP, SEXP d1SEXP, SEXP x0SEXP, SEXP mSEXP, SEXP kSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type ca(caSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rvmf_h(n, ca, d1, x0, m, k, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RiemSphere_cppdist_int_MtoN", (DL_FUNC) &_RiemSphere_cppdist_int_MtoN, 2},
    {"_RiemSphere_cppdist_ext_MtoN", (DL_FUNC) &_RiemSphere_cppdist_ext_MtoN, 2},
    {"_RiemSphere_cppdist_pair_int", (DL_FUNC) &_RiemSphere_cppdist_pair_int, 1},
    {"_RiemSphere_cppdist_pair_ext", (DL_FUNC) &_RiemSphere_cppdist_pair_ext, 1},
    {"_RiemSphere_cppdist_int_1toN", (DL_FUNC) &_RiemSphere_cppdist_int_1toN, 2},
    {"_RiemSphere_cppdist_ext_1toN", (DL_FUNC) &_RiemSphere_cppdist_ext_1toN, 2},
    {"_RiemSphere_engine_wmean", (DL_FUNC) &_RiemSphere_engine_wmean, 5},
    {"_RiemSphere_rvmf_h", (DL_FUNC) &_RiemSphere_rvmf_h, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_RiemSphere(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
