# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppdist_int_MtoN <- function(X, Y) {
    .Call('_RiemSphere_cppdist_int_MtoN', PACKAGE = 'RiemSphere', X, Y)
}

cppdist_ext_MtoN <- function(X, Y) {
    .Call('_RiemSphere_cppdist_ext_MtoN', PACKAGE = 'RiemSphere', X, Y)
}

cppdist_pair_int <- function(X) {
    .Call('_RiemSphere_cppdist_pair_int', PACKAGE = 'RiemSphere', X)
}

cppdist_pair_ext <- function(X) {
    .Call('_RiemSphere_cppdist_pair_ext', PACKAGE = 'RiemSphere', X)
}

cppdist_int_1toN <- function(x, Y) {
    .Call('_RiemSphere_cppdist_int_1toN', PACKAGE = 'RiemSphere', x, Y)
}

engine_wmean <- function(data, name, maxiter, eps, weights) {
    .Call('_RiemSphere_engine_wmean', PACKAGE = 'RiemSphere', data, name, maxiter, eps, weights)
}

rvmf_h <- function(n, ca, d1, x0, m, k, b) {
    .Call('_RiemSphere_rvmf_h', PACKAGE = 'RiemSphere', n, ca, d1, x0, m, k, b)
}

