# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

engine_wmean <- function(data, name, maxiter, eps, weights) {
    .Call('_RiemSphere_engine_wmean', PACKAGE = 'RiemSphere', data, name, maxiter, eps, weights)
}

rvmf_h <- function(n, ca, d1, x0, m, k, b) {
    .Call('_RiemSphere_rvmf_h', PACKAGE = 'RiemSphere', n, ca, d1, x0, m, k, b)
}

